FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi==0.110.0 \
    uvicorn==0.29.0 \
    sqlalchemy==1.4.53 \
    psycopg2-binary==2.9.9 \
    pandas==2.2.1 \
    scikit-learn \
    python-multipart \
    PyPDF2

COPY api/api.py .
EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]