x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:password@postgres:5432/job_intelligent
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    SELENIUM_URL: http://selenium:4444/wd/hub
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: job_intelligent
    DB_USER: admin
    DB_PASS: password
    FT_CLIENT_ID: ${FT_CLIENT_ID_api}
    FT_CLIENT_SECRET: ${FT_CLIENT_SECRET_api}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scrapers:/opt/airflow/scrapers
    - ./logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy
    selenium:
      condition: service_started
  networks:
    - job_net

services:

  postgres:
    image: postgres:15
    container_name: job_postgres
    environment:
      POSTGRES_DB: job_intelligent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d job_intelligent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job_net

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: job_selenium
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      SE_NODE_MAX_SESSIONS: 8
      SE_NODE_SESSION_TIMEOUT: 300
    networks:
      - job_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: job_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: job_intelligent
      DB_USER: admin
      DB_PASS: password
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - job_net
    restart: always

  airflow-init:
    <<: *airflow-common
    container_name: job_airflow_init
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@jobintelligent.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: job_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: job_airflow_scheduler
    command: scheduler
    restart: always

volumes:
  pg_data:

networks:
  job_net:
    driver: bridge