FROM apache/airflow:2.10.4-python3.11

USER airflow

COPY requirements.txt .

RUN pip install --no-cache-dir \
    --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.10.4/constraints-3.11.txt \
    -r requirements.txt

# Install spaCy models for CV parsing
# RUN python -m spacy download fr_core_news_md && \
#     python -m spacy download en_core_web_md
RUN pip install https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.7.0/fr_core_news_sm-3.7.0-py3-none-any.whl && \
    pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0-py3-none-any.whl